### ISSUE TITLE
switching Annoton forms should warn you if it will clear info that is already filled in

### ISSUE THREAD

**Issue by krchristie** [geneontology/noctua-form-legacy#49]
If you fill in the DEFAULT template with more than one BP term, and then switch to the BP ONLY template because you realize that you do not have a known MF to enter, only BP info, it loses everything except the 1st BP term.

It seems that it should warn you that switching templates will lose info that has been entered.

**Comment by tmushayahama** [comment]
@krchristie @vanaukenk I think this was addressed on the current form, by simply copying the values over. Form2.0 will handle it with a warning. However, I haven't really thought carefully of where place and trigger the cc only form . From the below, you can see the call to action button called "Add Activity" and the form has CC Only button from the dropdown. However, CC Only is not an activity 

![image](https://user-images.githubusercontent.com/2273929/62187864-8ea44880-b31f-11e9-88bb-b9f71ccba296.png)

**Comment by vanaukenk** [comment]
Closing this issue on the noctua-form-legacy tracker.  

The work is now under this ticket on the noctua-form tracker:

https://github.com/geneontology/noctua-form/issues/31
